sudo: required

services:
  - docker
  
language: cpp

compiler:
- g++

before_install:
  - sudo apt-get install build-essential git cmake -y
  
  - git clone https://github.com/DIT168Group9/DIT168Group9.git
  - cd DIT168Group9
  - mkdir build
  - cd build
  - cmake ..
  - make
  
