sudo: required

services:
  - docker
  
language: cpp

compiler:
- g++

before_install:
  # Installing lcov
  - wget http://downloads.sourceforge.net/ltp/lcov-1.13.tar.gz
  - tar -xvf lcov-1.13.tar.gz
  - cd lcov-1.13 && sudo make install
  - cd ..
  
  - docker pull dit168group9/dit168group9:cargroup9
  
script:
  - ci_env=`bash <(curl -s https://codecov.io/env)`
  - docker run $ci_env --rm --net=host dit168group9/dit168group9:cargroup9
  
after_success:
  # Creating report
   - lcov --directory . --capture --output-file coverage.info # capture coverage info
   - lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter out system
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) -t ce76b3fb-6076-4d11-a0fb-864ed5380fff
