sudo: required
services:
  - docker
language: cpp
compiler:
- g++
before_install:
  - git clone https://github.com/DIT168Group9/DIT168Group9.git
  - docker pull dit168group9/dit168group9:cargroup9
  - docker run --rm -ti --net=host dit168group9/dit168group9:cargroup9 bash
script:
  - docker exec dit168gorup9 mkdir build
  - docker exec dit168gorup9 cd build
  - docker exec dit168gorup9 cmake ..
  - docker exec dit168gorup9 make
after_success:
    # Creating report
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --capture --output-file coverage.info # capture coverage info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter out system
  - lcov --list coverage.info #debug info
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
